name: CI-CD

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::649536287246:role/githuboidcrole
          aws-region: us-east-2

      - run: terraform init
        working-directory: infra/terraform

      - run: terraform apply -auto-approve
        working-directory: infra/terraform

  build-and-push:
    runs-on: ubuntu-latest
    needs: terraform
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::649536287246:role/githuboidcrole
          aws-region: us-east-2

      - uses: aws-actions/amazon-ecr-login@v2

      - run: |
          IMAGE_URI=${{ secrets.ECR_REPOSITORY }}:latest
          docker build -t $IMAGE_URI ./app
          docker push $IMAGE_URI

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::649536287246:role/githuboidcrole
          aws-region: us-east-2

      - uses: azure/setup-kubectl@v3

      - run: aws eks update-kubeconfig --region us-east-2 --name dotnet-eks

      - run: |
          kubectl apply -f k8s/namespaces.yaml
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml